import type {Metadata} from 'next';
import styles from '@/app/(withoutHeader)/login/page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${styles.body}`}>
        {children}
      </body>
    </html>
  );
}
