import type { IScriptItem } from '@/components/ScriptsPanel/components/ScriptElement/ScriptElement.props';

export const mainPageUsecase = {
	title: 'Управление скриптами',
	subtitle: 'Найдите и запустите нужные скрипты или создайте новые',
};

export const APIScripts: IScriptItem[] = [
	{
		scriptId: 1,
		scriptTitle: 'Расчёт потерь давления в трубе или в узких пространствах транспорта',
		subtitle: 'Скрипт вычисляет потери давления в трубопроводе или скважине из-за трения о стенки трубы и гравитационных эффектов.',
		countOfRuns: 124,
		author: 'Иванов И.И.',
		data: new Date(),
	},
	{
		scriptId: 2,
		scriptTitle: 'Теплопотери в трубопроводах',
		subtitle: 'Определяет, сколько тепла теряет транспортируемая элемент по мере движения по трубе.',
		countOfRuns: 124,
		author: 'Пертов А.И.',
		data: new Date(),
	},
	{
		scriptId: 3,
		scriptTitle: 'Оценка износа материала трубы',
		subtitle: 'Скрипт прогнозирует скорость коррозии и механического износа трубы на основе условий эксплуатации.',
		countOfRuns: 124,
		author: 'Волт А.Ф.',
		data: new Date(),
	},
	{
		scriptId: 4,
		scriptTitle: 'Расчёт устойчивости ствола',
		subtitle: 'Скрипт оценивает риск обрушения стенок скважины или выдавливания бурового раствора.',
		countOfRuns: 124,
		author: 'Иванов И.И.',
		data: new Date(),
	},
	{
		scriptId: 5,
		scriptTitle: 'Оптимизация режимов прокачки',
		subtitle: 'Определяет оптимальные параметры работы насосных станций для минимизации энергозатрат.',
		countOfRuns: 87,
		author: 'Сидоров В.К.',
		data: new Date(),
	},
	{
		scriptId: 6,
		scriptTitle: 'Анализ гидроударов',
		subtitle: 'Прогнозирует последствия резкого изменения скорости потока в трубопроводных системах.',
		countOfRuns: 56,
		author: 'Петров А.И.',
		data: new Date(),
	},
	{
		scriptId: 7,
		scriptTitle: 'Расчёт толщины изоляции',
		subtitle: 'Определяет оптимальную толщину теплоизоляции для заданных температурных условий.',
		countOfRuns: 142,
		author: 'Козлова Е.С.',
		data: new Date(),
	},
	{
		scriptId: 8,
		scriptTitle: 'Моделирование двухфазных потоков',
		subtitle: 'Анализирует поведение газожидкостных смесей в трубопроводах.',
		countOfRuns: 78,
		author: 'Волков Д.М.',
		data: new Date(),
	},
	{
		scriptId: 9,
		scriptTitle: 'Оценка остаточного ресурса оборудования',
		subtitle: 'Прогнозирует срок службы насосов и компрессоров на основе статистики отказов.',
		countOfRuns: 95,
		author: 'Иванов И.И.',
		data: new Date(),
	},
	{
		scriptId: 10,
		scriptTitle: 'Расчёт экономии от модернизации',
		subtitle: 'Оценивает финансовую эффективность замены устаревшего оборудования.',
		countOfRuns: 63,
		author: 'Смирнова О.П.',
		data: new Date(),
	},
	{
		scriptId: 11,
		scriptTitle: 'Анализ вибраций трубопроводов',
		subtitle: 'Выявляет опасные вибрационные режимы работы трубопроводных систем.',
		countOfRuns: 41,
		author: 'Фёдоров Г.Р.',
		data: new Date(),
	},
	{
		scriptId: 12,
		scriptTitle: 'Прогнозирование отложений',
		subtitle: 'Предсказывает образование парафиновых и солевых отложений в трубах.',
		countOfRuns: 112,
		author: 'Кузнецова Т.В.',
		data: new Date(),
	},
	{
		scriptId: 13,
		scriptTitle: 'Расчёт пропускной способности',
		subtitle: 'Определяет максимальный расход через трубопровод при заданных параметрах.',
		countOfRuns: 134,
		author: 'Петров А.И.',
		data: new Date(),
	},
	{
		scriptId: 14,
		scriptTitle: 'Оптимизация маршрута трубопровода',
		subtitle: 'Находит оптимальную трассировку с учётом рельефа и экологических ограничений.',
		countOfRuns: 52,
		author: 'Соколов Н.Д.',
		data: new Date(),
	},
	{
		scriptId: 15,
		scriptTitle: 'Анализ утечек',
		subtitle: 'Выявляет и локализует возможные места утечек в трубопроводных системах.',
		countOfRuns: 89,
		author: 'Иванов И.И.',
		data: new Date(),
	},
	{
		scriptId: 16,
		scriptTitle: 'Расчёт прочности при морозном пучении',
		subtitle: 'Оценивает воздействие сил морозного пучения на подземные трубопроводы.',
		countOfRuns: 47,
		author: 'Зайцева Л.К.',
		data: new Date(),
	},
	{
		scriptId: 17,
		scriptTitle: 'Моделирование аварийных сценариев',
		subtitle: 'Прогнозирует последствия разгерметизации трубопровода.',
		countOfRuns: 71,
		author: 'Волков Д.М.',
		data: new Date(),
	},
	{
		scriptId: 18,
		scriptTitle: 'Расчёт нагрузок на опоры',
		subtitle: 'Определяет распределение механических нагрузок на опорные конструкции.',
		countOfRuns: 58,
		author: 'Фёдоров Г.Р.',
		data: new Date(),
	},
	{
		scriptId: 19,
		scriptTitle: 'Анализ химической совместимости',
		subtitle: 'Проверяет материалы труб на устойчивость к транспортируемым средам.',
		countOfRuns: 83,
		author: 'Кузнецова Т.В.',
		data: new Date(),
	},
	{
		scriptId: 20,
		scriptTitle: 'Оптимизация диаметра трубопровода',
		subtitle: 'Находит экономически оптимальный диаметр для заданных условий эксплуатации.',
		countOfRuns: 67,
		author: 'Сидоров В.К.',
		data: new Date(),
	},
	{
		scriptId: 21,
		scriptTitle: 'Расчёт сейсмостойкости',
		subtitle: 'Оценивает поведение трубопроводных систем при сейсмических воздействиях.',
		countOfRuns: 39,
		author: 'Зайцева Л.К.',
		data: new Date(),
	},
	{
		scriptId: 22,
		scriptTitle: 'Расчёт теплового расширения',
		subtitle: 'Определяет компенсацию линейных расширений труб при температурных колебаниях',
		countOfRuns: 92,
		author: 'Теплов А.В.',
		data: new Date('2024-03-15'),
	},
	{
		scriptId: 23,
		scriptTitle: 'Анализ кавитационных процессов',
		subtitle: 'Выявляет зоны риска возникновения кавитации в насосном оборудовании',
		countOfRuns: 64,
		author: 'Кавинский М.П.',
		data: new Date('2024-04-02'),
	},
	{
		scriptId: 24,
		scriptTitle: 'Оптимизация системы очистки',
		subtitle: 'Расчёт эффективности фильтровальных установок и сепараторов',
		countOfRuns: 78,
		author: 'Чистова Е.Д.',
		data: new Date('2024-02-28'),
	},
	{
		scriptId: 25,
		scriptTitle: 'Моделирование запарафинивания',
		subtitle: 'Прогнозирует образование парафиновых отложений в нефтепроводах',
		countOfRuns: 105,
		author: 'Черных В.С.',
		data: new Date('2024-05-11'),
	},
	{
		scriptId: 26,
		scriptTitle: 'Расчёт систем дренажа',
		subtitle: 'Проектирование систем аварийного сброса и дренажа',
		countOfRuns: 53,
		author: 'Водова Г.Р.',
		data: new Date('2024-01-22'),
	},
	{
		scriptId: 27,
		scriptTitle: 'Анализ электрокоррозии',
		subtitle: 'Оценка влияния блуждающих токов на коррозионную активность',
		countOfRuns: 81,
		author: 'Электронов К.М.',
		data: new Date('2024-06-05'),
	},
	{
		scriptId: 28,
		scriptTitle: 'Расчёт газогидратообразования',
		subtitle: 'Прогнозирование условий образования газовых гидратов',
		countOfRuns: 47,
		author: 'Гидратов П.Л.',
		data: new Date('2024-03-30'),
	},
	{
		scriptId: 29,
		scriptTitle: 'Оптимизация системы катодной защиты',
		subtitle: 'Расчёт параметров станций катодной защиты трубопроводов',
		countOfRuns: 112,
		author: 'Защитный А.К.',
		data: new Date('2024-04-18'),
	},
	{
		scriptId: 30,
		scriptTitle: 'Моделирование размыва под опорами',
		subtitle: 'Анализ эрозионных процессов в речных переходах',
		countOfRuns: 59,
		author: 'Береговой С.В.',
		data: new Date('2024-05-29'),
	},
	{
		scriptId: 31,
		scriptTitle: 'Расчёт системы подогрева',
		subtitle: 'Определение параметров системы поддержания температуры',
		countOfRuns: 86,
		author: 'Термостатов Р.П.',
		data: new Date('2024-06-12'),
	},
	{
		scriptId: 32,
		scriptTitle: 'Моделирование размыва под опорами',
		subtitle: 'Анализ эрозионных процессов в речных переходах',
		countOfRuns: 59,
		author: 'Береговой С.В.',
		data: new Date('2024-05-29'),
	},
	{
		scriptId: 34,
		scriptTitle: 'Расчёт системы подогрева',
		subtitle: 'Определение параметров системы поддержания температуры',
		countOfRuns: 86,
		author: 'Термостатов Р.П.',
		data: new Date('2024-06-12'),
	},
	{
		scriptId: 35,
		scriptTitle: 'Моделирование размыва под опорами',
		subtitle: 'Анализ эрозионных процессов в речных переходах',
		countOfRuns: 59,
		author: 'Береговой С.В.',
		data: new Date('2024-05-29'),
	},
	{
		scriptId: 36,
		scriptTitle: 'Расчёт системы подогрева',
		subtitle: 'Определение параметров системы поддержания температуры',
		countOfRuns: 86,
		author: 'Термостатов Р.П.',
		data: new Date('2024-06-12'),
	},
	{
		scriptId: 37,
		scriptTitle: 'Моделирование размыва под опорами',
		subtitle: 'Анализ эрозионных процессов в речных переходах',
		countOfRuns: 59,
		author: 'Береговой С.В.',
		data: new Date('2024-05-29'),
	},
	{
		scriptId: 38,
		scriptTitle: 'Расчёт системы подогрева',
		subtitle: 'Определение параметров системы поддержания температуры',
		countOfRuns: 86,
		author: 'Термостатов Р.П.',
		data: new Date('2024-06-12'),
	}
];
